name: Build and Push Backend Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'backend/**'  # Only trigger on backend changes
  workflow_dispatch:  # Always allow manual trigger

jobs:
  build-backend:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract metadata for backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: teacherki/scratch4school-backend
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha,format=short
            type=raw,value=dev,enable={{is_default_branch}}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend  # Backend directory 
          file: ./backend/Dockerfile  # Backend Dockerfile
          push: true
          tags: teacherki/scratch4school-backend:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max