name: Build and Push Frontend Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Extract version from tag or use 'dev' for branch pushes
      - name: Set Docker tag
        id: set-tag
        run: |
          # Check if this was triggered by a tag
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            # Extract version number without 'v' prefix
            TAG="${GITHUB_REF#refs/tags/v}"
            echo "TAG=$TAG" >> $GITHUB_ENV
            echo "Using tag from git: $TAG"
          else
            # Default to 'dev' for branch pushes
            echo "TAG=dev" >> $GITHUB_ENV
            echo "Using default tag: dev"
          fi

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./  # Root directory for frontend
          file: ./Dockerfile  # Root Dockerfile for frontend
          push: true
          tags: teacherki/scratch4school-frontend:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max